name: Self-healing CI

on:
  push:
    branches:
      - main
      - feat/self-heal-ci-sheets-validator
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  ci:
    name: Lint & tests (safe)
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install base deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff black isort || true

      - name: Lint (non-blocking)
        run: |
          ruff --fix . || true
          isort . || true
          black . || true

      - name: Run pytest (non-blocking)
        run: |
          set -o pipefail
          pytest -q || true

  validate_sheets:
    name: Google Sheets validator
    runs-on: ubuntu-latest
    needs: ci
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Skip (secrets missing)
        if: ${{ env.SHEET_ID == '' || env.GOOGLE_APPLICATION_CREDENTIALS_JSON == '' }}
        run: |
          echo "Secrets SHEET_ID / GOOGLE_APPLICATION_CREDENTIALS_JSON are not set. Skipping validator."

      - name: Install validator deps
        if: ${{ env.SHEET_ID != '' && env.GOOGLE_APPLICATION_CREDENTIALS_JSON != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2

      - name: Run validator
        if: ${{ env.SHEET_ID != '' && env.GOOGLE_APPLICATION_CREDENTIALS_JSON != '' }}
        env:
          SHEET_ID: ${{ env.SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ env.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: python validate_google_sheet.py
