name: Self-healing CI

on:
  push:
    branches: [ main, feat/self-heal-ci-sheets-validator ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  ci:
    name: Lint & tests (safe)
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install base deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff black isort || true
      - name: Lint (non-blocking)
        run: |
          ruff --fix . || true
          isort . || true
          black . || true
      - name: Run pytest (non-blocking)
        run: |
          set -o pipefail
          pytest -q || true

  validate_sheets:
    name: Google Sheets validator (runs only if secrets exist)
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ secrets.SHEET_ID && secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install validator deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2
      - name: Run validator
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: python validate_google_sheet.py
